---
name: config_network_postgresql_list.write.dependency
type: dependency
meta:
  tags: [
      "config_network_postgresql",
      #### #### #### #### #### #### #### #### #### #### #### ####
      "type_dependency",
      #### #### #### #### #### #### #### #### #### #### #### ####
      # #
      "event_write",
      "event_write_close",
      "event_write_config",
    ]

  authors: [" hyde - Benjamin Collas - DIGISQUAD - https://www.digisquad.com"]
  comments:
    - dependency rule - identify write config_network_postgresql_list.write.dependency

#### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

matches:
  $r_01: .data.path ~= ".*/etc/postgresql/.*?/main/postgresql.conf($|/)?"
  $r_02: .data.path ~= ".*/etc/postgresql/.*?/main/pg_hba.conf($|/)?"
  $r_03: .data.path ~= ".*/etc/postgresql/.*?/main/pg_ident.conf($|/)?"
  $r_04: .data.path ~= "^/etc/postgresql(/|$)"

condition: any of $r_
