---
name: config_network_apache_list.write.dependency
type: dependency
meta:
  tags: [
      "config_network_apache",
      #### #### #### #### #### #### #### #### #### #### #### ####
      "type_dependency",
      #### #### #### #### #### #### #### #### #### #### #### ####
      # #
      "event_write",
      "event_write_close",
      "event_write_config",
    ]

  authors: [" hyde - Benjamin Collas - DIGISQUAD - https://www.digisquad.com"]
  comments:
    - dependency rule - identify write config_network_apache_list.write.dependency

#### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

matches:
  $r_01: .data.path ~= ".*/etc/apache2/apache2.conf($|/)?"
  $r_02: .data.path ~= "^/etc/apache2/conf.d(/|$)"
  $r_03: .data.path ~= "^/etc/apache2/sites-available(/|$)"
  $r_04: .data.path ~= "^/etc/apache2/sites-enabled(/|$)"
  $r_05: .data.path ~= "^/etc/httpd(/|$)"

condition: any of $r_
