---
name: config_system_apparmor_list.write.dependency
type: dependency
meta:
  tags: [
      "config_system_apparmor",
      #### #### #### #### #### #### #### #### #### #### #### ####
      "type_dependency",
      #### #### #### #### #### #### #### #### #### #### #### ####
      # #
      "event_write",
      "event_write_close",
      "event_write_config",
    ]

  authors: [" hyde - Benjamin Collas - DIGISQUAD - https://www.digisquad.com"]
  comments:
    - dependency rule - identify write config_system_apparmor_list.write.dependency

#### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

matches:
  $r_01: .data.path ~= "^/etc/apparmor.d(/|$)"
  $r_02: .data.path ~= ".*/etc/apparmor/apparmor.conf($|/)?"
  $r_03: .data.path ~= ".*/etc/default/apparmor($|/)?"

condition: any of $r_
