---
name: config_network_ssh_list.write.dependency
type: dependency
meta:
  tags: [
      "config_network_ssh",
      #### #### #### #### #### #### #### #### #### #### #### ####
      "type_dependency",
      #### #### #### #### #### #### #### #### #### #### #### ####
      # #
      "event_write",
      "event_write_close",
      "event_write_config",
    ]

  authors: [" hyde - Benjamin Collas - DIGISQUAD - https://www.digisquad.com"]
  comments:
    - dependency rule - identify write config_network_ssh_list.write.dependency

#### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

matches:
  $r_01: .data.path ~= ".*/etc/ssh/sshd_config($|/)?"
  $r_02: .data.path ~= "^/etc/ssh/sshd_config.d(/|$)"

  $r_03: .data.path ~= ".*/etc/ssh/ssh_config($|/)?"
  $r_04: .data.path ~= "^/etc/ssh/ssh_config.d(/|$)"

condition: any of $r_
